version: '3.3'

services:
  # db: 
  #   image: postgres:11-alpine
  #   environment:
  #     - POSTGRES_PASSWORD=password 
  #   ports: 
  #     - "5432:5432"
  #   volumes:
  #     - "dbdata:/var/lib/postgresql/data"
  
  redis:
    image: redis:6.2.12-alpine
    ports:
      - "6379:6379"
  
  web:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
 #     - db 
      - redis 
    environment:
#      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

volumes:
  dbdata: