# run this command to set this configuration: 'bundle exec sidekiq -C config/sidekiq.yml'
# then open a new tab and run 'rails console' use the variable below to see the connection
# between Redis and Sidekiq 'redis_config = Sidekiq.redis { |conn| conn.info }'

# It going to return:
#   {"redis_version"=>"X.X.X",
#     ...


# Clean UI Sidekiq Monitoring. First run 'rails c' then run 'Sidekiq.redis { |conn| conn.flushdb }'
---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - critical
  - default
  - low
  - mailers