# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: Country.create(name_country:"Star Wars") }, { name: Country.create(name_country:"Lord of the Rings") }])
#   Character.create(name: Country.create(name_country:"Luke"), movie: movies.first)



Country.create(name_country: "Albania")
Country.create(name_country:"Algeria")
Country.create(name_country:"American Samoa")
Country.create(name_country:"Andorra")
Country.create(name_country:"Angola")
Country.create(name_country:"Anguilla")
Country.create(name_country:"Antarctica")
Country.create(name_country:"Antigua and Barbuda")
Country.create(name_country:"Argentina")
Country.create(name_country:"Armenia")
Country.create(name_country:"Aruba")
Country.create(name_country: "Australia")
Country.create(name_country: "Australia")
Country.create(name_country:"Australia")
Country.create(name_country:"Australia")
Country.create(name_country:"Austria")
Country.create(name_country:"Azerbaijan")
Country.create(name_country:"Bahamas")
Country.create(name_country:"Bahrain")
Country.create(name_country:"Bangladesh")
Country.create(name_country:"Barbados")
Country.create(name_country:"Belarus")
Country.create(name_country:"Belgium")
Country.create(name_country:"Belize")
Country.create(name_country:"Benin")
Country.create(name_country:"Bermuda")
Country.create(name_country:"Bhutan")
Country.create(name_country:"Bolivia")
Country.create(name_country:"Bonaire, Sint Eustatius and Saba")
Country.create(name_country:"Bosnia and Herzegovina")
Country.create(name_country:"Botswana")
Country.create(name_country:"Bouvet Island")
Country.create(name_country:"Brazil")
Country.create(name_country:"British Indian Ocean Territory")
Country.create(name_country:"Brunei Darussalam")
Country.create(name_country:"Bulgaria")
Country.create(name_country:"Burkina Faso")
Country.create(name_country:"Burundi")
Country.create(name_country:"Cabo Verde")
Country.create(name_country:"Cambodia")
Country.create(name_country:"Cameroon")
Country.create(name_country:"Canada")
Country.create(name_country:"Cayman Islands")
Country.create(name_country:"Central African Republic")
Country.create(name_country:"Chad")
Country.create(name_country:"Chile")
Country.create(name_country:"China")
Country.create(name_country:"Christmas Island")
Country.create(name_country:"Cocos (Keeling) Islands")
Country.create(name_country:"Colombia")
Country.create(name_country:"Comoros")
Country.create(name_country:"Congo")
Country.create(name_country:"Congo, The Democratic Republic of the")
Country.create(name_country:"Cook Islands")
Country.create(name_country:"Costa Rica")
Country.create(name_country:"Croatia")
Country.create(name_country:"Cuba")
Country.create(name_country:"Curaçao")
Country.create(name_country:"Cyprus")
Country.create(name_country:"Czechia")
Country.create(name_country:"Côte d'Ivoire")
Country.create(name_country:"Denmark")
Country.create(name_country:"Djibouti")
Country.create(name_country:"Dominica")
Country.create(name_country:"Dominican Republic")
Country.create(name_country:"Ecuador")
Country.create(name_country:"Egypt")
Country.create(name_country:"El Salvador")
Country.create(name_country:"Equatorial Guinea")
Country.create(name_country:"Eritrea")
Country.create(name_country:"Estonia")
Country.create(name_country:"Eswatini")
Country.create(name_country:"Ethiopia")
Country.create(name_country:"Falkland Islands (Malvinas)")
Country.create(name_country:"Faroe Islands")
Country.create(name_country:"Fiji")
Country.create(name_country:"Finland")
Country.create(name_country:"France")
Country.create(name_country:"French Guiana")
Country.create(name_country:"French Polynesia")
Country.create(name_country:"French Southern Territories")
Country.create(name_country:"Gabon")
Country.create(name_country:"Gambia")
Country.create(name_country:"Georgia")
Country.create(name_country:"Germany")
Country.create(name_country:"Ghana")
Country.create(name_country:"Gibraltar")
Country.create(name_country:"Greece")
Country.create(name_country:"Greenland")
Country.create(name_country:"Grenada")
Country.create(name_country:"Guadeloupe")
Country.create(name_country:"Guam")
Country.create(name_country:"Guatemala")
Country.create(name_country:"Guernsey")
Country.create(name_country:"Guinea")
Country.create(name_country:"Guinea-Bissau")
Country.create(name_country:"Guyana")
Country.create(name_country:"Haiti")
Country.create(name_country:"Heard Island and McDonald Islands")
Country.create(name_country:"Holy See (Vatican City State)")
Country.create(name_country:"Honduras")
Country.create(name_country:"Hong Kong")
Country.create(name_country:"Hungary")
Country.create(name_country:"Iceland")
Country.create(name_country:"India")
Country.create(name_country:"Indonesia")
Country.create(name_country:"Iran, Islamic Republic of")
Country.create(name_country:"Iraq")
Country.create(name_country:"Ireland")
Country.create(name_country:"Isle of Man")
Country.create(name_country:"Israel")
Country.create(name_country:"Italy")
Country.create(name_country:"Jamaica")
Country.create(name_country:"Japan")
Country.create(name_country:"Jersey")
Country.create(name_country:"Jordan")
Country.create(name_country:"Kazakhstan")
Country.create(name_country:"Kenya")
Country.create(name_country:"Kiribati")
Country.create(name_country:"Kuwait")
Country.create(name_country:"Kyrgyzstan")
Country.create(name_country:"Lao People's Democratic Republic")
Country.create(name_country:"Latvia")
Country.create(name_country:"Lebanon")
Country.create(name_country:"Lesotho")
Country.create(name_country:"Liberia")
Country.create(name_country:"Libya")
Country.create(name_country:"Liechtenstein")
Country.create(name_country:"Lithuania")
Country.create(name_country:"Luxembourg")
Country.create(name_country:"Macao")
Country.create(name_country:"Madagascar")
Country.create(name_country:"Malawi")
Country.create(name_country:"Malaysia")
Country.create(name_country:"Maldives")
Country.create(name_country:"Mali")
Country.create(name_country:"Malta")
Country.create(name_country:"Marshall Islands")
Country.create(name_country:"Martinique")
Country.create(name_country:"Mauritania")
Country.create(name_country:"Mauritius")
Country.create(name_country:"Mayotte")
Country.create(name_country:"Mexico")
Country.create(name_country:"Micronesia, Federated States of")
Country.create(name_country:"Moldova")
Country.create(name_country:"Monaco")
Country.create(name_country:"Mongolia")
Country.create(name_country:"Montenegro")
Country.create(name_country:"Montserrat")
Country.create(name_country:"Morocco")
Country.create(name_country:"Mozambique")
Country.create(name_country:"Myanmar")
Country.create(name_country:"Namibia")
Country.create(name_country:"Nauru")
Country.create(name_country:"Nepal")
Country.create(name_country:"Netherlands")
Country.create(name_country:"New Caledonia")
Country.create(name_country:"New Zealand")
Country.create(name_country:"Nicaragua")
Country.create(name_country:"Niger")
Country.create(name_country:"Nigeria")
Country.create(name_country:"Niue")
Country.create(name_country:"Norfolk Island")
Country.create(name_country:"North Korea")
Country.create(name_country:"North Macedonia")
Country.create(name_country:"Northern Mariana Islands")
Country.create(name_country:"Norway")
Country.create(name_country:"Oman")
Country.create(name_country:"Pakistan")
Country.create(name_country:"Palau")
Country.create(name_country:"Palestine, State of")
Country.create(name_country:"Panama")
Country.create(name_country:"Papua New Guinea")
Country.create(name_country:"Paraguay")
Country.create(name_country:"Peru")
Country.create(name_country:"Philippines")
Country.create(name_country:"Pitcairn")
Country.create(name_country:"Poland")
Country.create(name_country:"Portugal")
Country.create(name_country:"Puerto Rico")
Country.create(name_country:"Qatar")
Country.create(name_country:"Romania")
Country.create(name_country:"Russian Federation")
Country.create(name_country:"Rwanda")
Country.create(name_country:"Réunion")
Country.create(name_country:"Saint Barthélemy")
Country.create(name_country:"Saint Helena, Ascension and Tristan da Cunha")
Country.create(name_country:"Saint Kitts and Nevis")
Country.create(name_country:"Saint Lucia")
Country.create(name_country:"Saint Martin (French part)")
Country.create(name_country:"Saint Pierre and Miquelon")
Country.create(name_country:"Saint Vincent and the Grenadines")
Country.create(name_country:"Samoa")
Country.create(name_country:"San Marino")
Country.create(name_country:"Sao Tome and Principe")
Country.create(name_country:"Saudi Arabia")
Country.create(name_country:"Senegal")
Country.create(name_country:"Serbia")
Country.create(name_country:"Seychelles")
Country.create(name_country:"Sierra Leone")
Country.create(name_country:"Singapore")
Country.create(name_country:"Sint Maarten (Dutch part)")
Country.create(name_country:"Slovakia")
Country.create(name_country:"Slovenia")
Country.create(name_country:"Solomon Islands")
Country.create(name_country:"Somalia")
Country.create(name_country:"South Africa")
Country.create(name_country:"South Georgia and the South Sandwich Islands")
Country.create(name_country:"South Korea")
Country.create(name_country:"South Sudan")
Country.create(name_country:"Spain")
Country.create(name_country:"Sri Lanka")
Country.create(name_country:"Sudan")
Country.create(name_country:"Suriname")
Country.create(name_country:"Svalbard and Jan Mayen")
Country.create(name_country:"Sweden")
Country.create(name_country:"Switzerland")
Country.create(name_country:"Syrian Arab Republic")
Country.create(name_country:"Taiwan")
Country.create(name_country:"Tajikistan")
Country.create(name_country:"Tanzania")
Country.create(name_country:"Thailand")
Country.create(name_country:"Timor-Leste")
Country.create(name_country:"Togo")
Country.create(name_country:"Tokelau")
Country.create(name_country:"Tonga")
Country.create(name_country:"Trinidad and Tobago")
Country.create(name_country:"Tunisia")
Country.create(name_country:"Turkey")
Country.create(name_country:"Turkmenistan")
Country.create(name_country:"Turks and Caicos Islands")
Country.create(name_country:"Tuvalu")
Country.create(name_country:"Uganda")
Country.create(name_country:"Ukraine")
Country.create(name_country:"United Arab Emirates")
Country.create(name_country:"United Kingdom")
Country.create(name_country:"United States")
Country.create(name_country:"United States Minor Outlying Islands")
Country.create(name_country:"Uruguay")
Country.create(name_country:"Uzbekistan")
Country.create(name_country:"Vanuatu")
Country.create(name_country:"Venezuela")
Country.create(name_country:"Vietnam")
Country.create(name_country:"Virgin Islands, British")
Country.create(name_country:"Virgin Islands, U.s")
Country.create(name_country:"Wallis and Futuna")
Country.create(name_country:"Western Sahara")
Country.create(name_country:"Yemen")
Country.create(name_country:"Zambia")
Country.create(name_country:"Zimbabwe")
Country.create(name_country:"Åland Islands")











1.times do 
   vicente = User.new({
        username: "Vicente",
        country_id: 1,
        localization_description: "Luanda/Kilamba", 
        email: "Vicente@gmail.com",
        password: "Vicente",
        password_confirmation: "Vicente",
        type_subscription: "Company")
        })
  vicente.save

   galinha = User.new({
    username: "Galinha",
    country_id: 9,
    localization_description: "Luanda/Kilamba", 
    email: "galinha@gmail.com",
    password: "galinha",
    password_confirmation: "galinha",
    type_subscription: "Candidate"
    })
    galinha.save

end

Category.create(name: "Programming")
Category.create(name: "Construction")
Category.create(name: "Movie")
Category.create(name: "Others")

6.times do |job_number|

    Job.create(
        title: "Ruby on rails Dev #{job_number}", 
        description: "Developer new feacture", 
        salary: 4500*job_number, 
        category_id: job_number,
        type_job: "Presencial",
        expiry_date: "2022/#{job_number}/14",
        user_id: 1

    )
    Job.create(
        title: "Phython Dev #{job_number}", 
        description: "Developer new application", 
        salary: 4500*job_number, 
        category_id: job_number,
        type_job: "Remote",
        expiry_date: "2022/#{job_number}/14",
        user_id: 2

    )
end
